extensive refactoring
theimo1221/NodeMerlinWrtApi pull request #3
Opened 2024-11-28 06:53 UTC by smoebody

* adds function docs
* utilises built in functions for sanitising
* caches login responses as promise
* caches getClientList response as promise
* introduces getClientByMac(), getIpTraffic()
* introduces custom exceptions
* changes code style, updates packages
* adds multiple node build targets, removes v16

2024-11-28 07:22 UTC, smoebody commented
@theimo1221 Please can you have a look and tell me whether you are ok with this?

2024-11-28 21:21 UTC, theimo1221 commented
Thanks @smoebody 

Personally I'd prefer the usage of semicolons like microsoft themself (e.g.`https://github.com/microsoft/TypeScript/tree/main`) as this reduces pitfalls for non experienced coders.

2024-11-28 21:22 UTC, theimo1221 requested changes

2024-11-28 21:22 UTC, theimo1221 commented on src/Models/iptraffic.ts
Why is this not a normal interface and or class?

2024-11-29 09:18 UTC, smoebody commented on src/Models/iptraffic.ts
I don't understand, why should it be? Types are totally sufficient and there is no need for interfaces or even a class. 
Maybe it should not be in Models. But then there is also the enum `DeviceAction` and other interface-only declarations...

2024-12-07 11:59 UTC, smoebody commented on src/Models/iptraffic.ts
I changed it to be an interface

2024-12-10 16:02 UTC, theimo1221 approved these changes

2024-12-10 16:02 UTC, theimo1221 commented on src/Models/iptraffic.ts
I might be a more conservative typescript developer, thus I discourage usage of types and especially nested types like `clients: (Traffic & { mac: string })[]`.
Additionally in my opinion there should only be one type/class/interface per file

2024-12-10 16:02 UTC, merged